import type { GlobalThemeFamily, GlobalThemePreset, ResolvedGlobalThemeMode } from './types'

type GlobalThemeFamilyOption = {
  id: GlobalThemeFamily
  name: string
}

export const GLOBAL_THEME_FAMILY_OPTIONS: GlobalThemeFamilyOption[] = [
  { id: 'default', name: '默认' },
  { id: 'bambooGrove', name: '清雅竹林' },
  { id: 'palacePlum', name: '宫墙红梅' },
  { id: 'mistyJiangnan', name: '烟雨水乡' },
  { id: 'luoyangPeony', name: '洛都牡丹' },
  { id: 'dunhuangApsaras', name: '敦煌飞天' },
  { id: 'autumnOsmanthus', name: '金秋丹桂' },
]

export const DEFAULT_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'default',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#f5f6fa',
    '--bg-surface': '#ffffff',
    '--bg-surface-alt': '#f8faff',
    '--bg-surface-muted': '#f4f8ff',
    '--bg-soft': '#f6f8fc',
    '--text-primary': '#1f1f1f',
    '--text-strong': '#182338',
    '--text-secondary': '#72809a',
    '--text-muted': '#7b859a',
    '--text-accent': '#2f4f87',
    '--text-on-accent': '#ffffff',
    '--border-soft': '#e6e8ef',
    '--border-muted': '#edf0f6',
    '--border-strong': '#d9dfe8',
    '--overlay-glass': 'rgba(247, 250, 255, 0.58)',
    '--overlay-panel': 'rgba(255, 255, 255, 0.72)',
    '--overlay-border-top': 'rgba(218, 224, 237, 0.72)',
    '--shadow-nav': 'rgba(31, 35, 46, 0.08)',
    '--button-soft-bg': '#ecf2ff',
    '--button-soft-bg-active': '#dee8ff',
    '--button-soft-text': '#2f4f87',
    '--accent-primary': '#1677ff',
    '--avatar-grad-start': '#f7faff',
    '--avatar-grad-end': '#dbe8ff',
    '--avatar-border': '#d7e3ff',
    '--avatar-text': '#4a5f85',
    '--switch-active-border': '#7eaef6',
  },
}

export const DEFAULT_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'default',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#12161d',
    '--bg-surface': '#1b212b',
    '--bg-surface-alt': '#212938',
    '--bg-surface-muted': '#232d3c',
    '--bg-soft': '#252f40',
    '--text-primary': '#e4e9f2',
    '--text-strong': '#f1f4fb',
    '--text-secondary': '#a8b2c5',
    '--text-muted': '#98a4bb',
    '--text-accent': '#c8d9ff',
    '--text-on-accent': '#f4f8ff',
    '--border-soft': '#2f3a4f',
    '--border-muted': '#334158',
    '--border-strong': '#3a4a64',
    '--overlay-glass': 'rgba(20, 26, 36, 0.76)',
    '--overlay-panel': 'rgba(31, 40, 56, 0.76)',
    '--overlay-border-top': 'rgba(71, 86, 112, 0.72)',
    '--shadow-nav': 'rgba(5, 8, 12, 0.36)',
    '--button-soft-bg': '#2a3750',
    '--button-soft-bg-active': '#334564',
    '--button-soft-text': '#d1deff',
    '--accent-primary': '#7fb1ff',
    '--avatar-grad-start': '#263448',
    '--avatar-grad-end': '#344867',
    '--avatar-border': '#3f5476',
    '--avatar-text': '#d5dff2',
    '--switch-active-border': '#89b6ff',
  },
}

export const PALACE_PLUM_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'palacePlum',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#f6f0ef',
    '--bg-surface': '#fff9f8',
    '--bg-surface-alt': '#fcf2f0',
    '--bg-surface-muted': '#f8e8e5',
    '--bg-soft': '#f4e4e1',
    '--text-primary': '#3f2329',
    '--text-strong': '#32171d',
    '--text-secondary': '#7f565f',
    '--text-muted': '#93676f',
    '--text-accent': '#9b1e64',
    '--text-on-accent': '#fff7f8',
    '--border-soft': '#e9d6d8',
    '--border-muted': '#f0e1e2',
    '--border-strong': '#debec4',
    '--overlay-glass': 'rgba(255, 246, 245, 0.62)',
    '--overlay-panel': 'rgba(255, 250, 249, 0.76)',
    '--overlay-border-top': 'rgba(229, 198, 205, 0.72)',
    '--shadow-nav': 'rgba(66, 29, 37, 0.14)',
    '--button-soft-bg': '#f2dde2',
    '--button-soft-bg-active': '#ebcfd7',
    '--button-soft-text': '#7f274f',
    '--accent-primary': '#9b1e64',
    '--avatar-grad-start': '#fff4f5',
    '--avatar-grad-end': '#f0d9de',
    '--avatar-border': '#e4c5cc',
    '--avatar-text': '#6e3547',
    '--switch-active-border': '#c54b86',
  },
}

export const PALACE_PLUM_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'palacePlum',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#1b1319',
    '--bg-surface': '#251922',
    '--bg-surface-alt': '#2b1f29',
    '--bg-surface-muted': '#302330',
    '--bg-soft': '#352733',
    '--text-primary': '#f1dee7',
    '--text-strong': '#f8eaf1',
    '--text-secondary': '#c5a2b0',
    '--text-muted': '#b58f9d',
    '--text-accent': '#f0a3c8',
    '--text-on-accent': '#2f0f1e',
    '--border-soft': '#4a3442',
    '--border-muted': '#5a3e50',
    '--border-strong': '#68475d',
    '--overlay-glass': 'rgba(35, 23, 31, 0.78)',
    '--overlay-panel': 'rgba(45, 30, 40, 0.8)',
    '--overlay-border-top': 'rgba(115, 79, 98, 0.72)',
    '--shadow-nav': 'rgba(8, 4, 7, 0.46)',
    '--button-soft-bg': '#4a2f3f',
    '--button-soft-bg-active': '#5a3850',
    '--button-soft-text': '#f4c2da',
    '--accent-primary': '#c84a87',
    '--avatar-grad-start': '#402a37',
    '--avatar-grad-end': '#5a384d',
    '--avatar-border': '#6e4660',
    '--avatar-text': '#f0c7d9',
    '--switch-active-border': '#d86da3',
  },
}

export const BAMBOO_GROVE_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'bambooGrove',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#edf4f0',
    '--bg-surface': '#f7fcf9',
    '--bg-surface-alt': '#eef8f2',
    '--bg-surface-muted': '#e5f2ea',
    '--bg-soft': '#deeee4',
    '--text-primary': '#1f332c',
    '--text-strong': '#172821',
    '--text-secondary': '#4f6c61',
    '--text-muted': '#607d72',
    '--text-accent': '#006442',
    '--text-on-accent': '#f5fff9',
    '--border-soft': '#cfe2d8',
    '--border-muted': '#dcebe3',
    '--border-strong': '#bdd3c7',
    '--overlay-glass': 'rgba(242, 251, 245, 0.64)',
    '--overlay-panel': 'rgba(249, 255, 252, 0.78)',
    '--overlay-border-top': 'rgba(183, 211, 196, 0.72)',
    '--shadow-nav': 'rgba(16, 40, 31, 0.14)',
    '--button-soft-bg': '#dcefe5',
    '--button-soft-bg-active': '#cfe7db',
    '--button-soft-text': '#0f5a3c',
    '--accent-primary': '#006442',
    '--avatar-grad-start': '#eefaf2',
    '--avatar-grad-end': '#cfe6d8',
    '--avatar-border': '#bfd9c9',
    '--avatar-text': '#2a5647',
    '--switch-active-border': '#2d8f6a',
  },
}

export const BAMBOO_GROVE_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'bambooGrove',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#121d19',
    '--bg-surface': '#192824',
    '--bg-surface-alt': '#20312c',
    '--bg-surface-muted': '#253831',
    '--bg-soft': '#2a4038',
    '--text-primary': '#dcece3',
    '--text-strong': '#eef8f2',
    '--text-secondary': '#a0bbaf',
    '--text-muted': '#8fa89d',
    '--text-accent': '#7dd6b1',
    '--text-on-accent': '#10211a',
    '--border-soft': '#315045',
    '--border-muted': '#3b5e52',
    '--border-strong': '#486d60',
    '--overlay-glass': 'rgba(21, 34, 29, 0.78)',
    '--overlay-panel': 'rgba(30, 47, 41, 0.8)',
    '--overlay-border-top': 'rgba(83, 122, 107, 0.74)',
    '--shadow-nav': 'rgba(3, 10, 8, 0.48)',
    '--button-soft-bg': '#2b433b',
    '--button-soft-bg-active': '#36534a',
    '--button-soft-text': '#b7e8d2',
    '--accent-primary': '#3fa97f',
    '--avatar-grad-start': '#294138',
    '--avatar-grad-end': '#3a5a4d',
    '--avatar-border': '#48695b',
    '--avatar-text': '#c4e8d7',
    '--switch-active-border': '#6bc59f',
  },
}

export const MISTY_JIANGNAN_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'mistyJiangnan',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#edf1f4',
    '--bg-surface': '#f8fbfd',
    '--bg-surface-alt': '#eef3f7',
    '--bg-surface-muted': '#e4ebf1',
    '--bg-soft': '#dde5ec',
    '--text-primary': '#273137',
    '--text-strong': '#1f2a2f',
    '--text-secondary': '#5f717b',
    '--text-muted': '#6e808b',
    '--text-accent': '#426666',
    '--text-on-accent': '#f4f8fb',
    '--border-soft': '#cfd9e1',
    '--border-muted': '#dbe3ea',
    '--border-strong': '#bfcbd5',
    '--overlay-glass': 'rgba(244, 248, 252, 0.64)',
    '--overlay-panel': 'rgba(250, 253, 255, 0.78)',
    '--overlay-border-top': 'rgba(186, 202, 214, 0.72)',
    '--shadow-nav': 'rgba(25, 39, 49, 0.12)',
    '--button-soft-bg': '#dde7ee',
    '--button-soft-bg-active': '#d0dde6',
    '--button-soft-text': '#3f6262',
    '--accent-primary': '#426666',
    '--avatar-grad-start': '#edf3f7',
    '--avatar-grad-end': '#cedbe4',
    '--avatar-border': '#becfda',
    '--avatar-text': '#48606c',
    '--switch-active-border': '#6f9698',
  },
}

export const MISTY_JIANGNAN_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'mistyJiangnan',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#121a21',
    '--bg-surface': '#19232c',
    '--bg-surface-alt': '#1f2d37',
    '--bg-surface-muted': '#253641',
    '--bg-soft': '#2b3e4b',
    '--text-primary': '#dce7ee',
    '--text-strong': '#ecf4f9',
    '--text-secondary': '#a3b5c2',
    '--text-muted': '#91a5b3',
    '--text-accent': '#9dc3c3',
    '--text-on-accent': '#132227',
    '--border-soft': '#314453',
    '--border-muted': '#3a4f61',
    '--border-strong': '#45607a',
    '--overlay-glass': 'rgba(20, 31, 39, 0.78)',
    '--overlay-panel': 'rgba(28, 43, 54, 0.8)',
    '--overlay-border-top': 'rgba(78, 104, 124, 0.74)',
    '--shadow-nav': 'rgba(6, 10, 15, 0.48)',
    '--button-soft-bg': '#2c4150',
    '--button-soft-bg-active': '#375063',
    '--button-soft-text': '#c4dde0',
    '--accent-primary': '#5e898c',
    '--avatar-grad-start': '#2d4050',
    '--avatar-grad-end': '#3b5366',
    '--avatar-border': '#4a6780',
    '--avatar-text': '#c9dde8',
    '--switch-active-border': '#84b0b4',
  },
}

export const LUOYANG_PEONY_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'luoyangPeony',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#f5eff4',
    '--bg-surface': '#fffbff',
    '--bg-surface-alt': '#f9f2f8',
    '--bg-surface-muted': '#f3e8f2',
    '--bg-soft': '#eedfeb',
    '--text-primary': '#352230',
    '--text-strong': '#2c1727',
    '--text-secondary': '#765467',
    '--text-muted': '#866476',
    '--text-accent': '#9b1e64',
    '--text-on-accent': '#fff7fc',
    '--border-soft': '#e4d3df',
    '--border-muted': '#ecdeea',
    '--border-strong': '#d7bfd1',
    '--overlay-glass': 'rgba(252, 245, 251, 0.64)',
    '--overlay-panel': 'rgba(255, 249, 254, 0.78)',
    '--overlay-border-top': 'rgba(218, 193, 214, 0.72)',
    '--shadow-nav': 'rgba(55, 24, 48, 0.14)',
    '--button-soft-bg': '#eedeea',
    '--button-soft-bg-active': '#e6d0e0',
    '--button-soft-text': '#862453',
    '--accent-primary': '#9b1e64',
    '--avatar-grad-start': '#fdf2fa',
    '--avatar-grad-end': '#efd7e8',
    '--avatar-border': '#e2c1d7',
    '--avatar-text': '#6f3b58',
    '--switch-active-border': '#c34f8d',
  },
}

export const LUOYANG_PEONY_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'luoyangPeony',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#19121a',
    '--bg-surface': '#241825',
    '--bg-surface-alt': '#2d1e2e',
    '--bg-surface-muted': '#342436',
    '--bg-soft': '#3b2a3d',
    '--text-primary': '#f0dde9',
    '--text-strong': '#f8ebf3',
    '--text-secondary': '#c4a5b9',
    '--text-muted': '#b793a8',
    '--text-accent': '#f3a6cd',
    '--text-on-accent': '#320f23',
    '--border-soft': '#4c3550',
    '--border-muted': '#5c3e61',
    '--border-strong': '#6b4971',
    '--overlay-glass': 'rgba(32, 22, 33, 0.78)',
    '--overlay-panel': 'rgba(43, 29, 44, 0.8)',
    '--overlay-border-top': 'rgba(113, 77, 118, 0.74)',
    '--shadow-nav': 'rgba(10, 5, 9, 0.48)',
    '--button-soft-bg': '#4e3251',
    '--button-soft-bg-active': '#603f64',
    '--button-soft-text': '#f1c5dd',
    '--accent-primary': '#c74889',
    '--avatar-grad-start': '#452b47',
    '--avatar-grad-end': '#5c3a60',
    '--avatar-border': '#6f4773',
    '--avatar-text': '#f0cbe0',
    '--switch-active-border': '#d972a9',
  },
}

export const DUNHUANG_APSARAS_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'dunhuangApsaras',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#f3f1ec',
    '--bg-surface': '#fffdf8',
    '--bg-surface-alt': '#f8f3ea',
    '--bg-surface-muted': '#f2e8db',
    '--bg-soft': '#ebdfd0',
    '--text-primary': '#39342d',
    '--text-strong': '#2f2b24',
    '--text-secondary': '#75695a',
    '--text-muted': '#857866',
    '--text-accent': '#008792',
    '--text-on-accent': '#f5ffff',
    '--border-soft': '#dfd2c0',
    '--border-muted': '#e8ddcf',
    '--border-strong': '#d0bea6',
    '--overlay-glass': 'rgba(252, 248, 241, 0.64)',
    '--overlay-panel': 'rgba(255, 251, 245, 0.78)',
    '--overlay-border-top': 'rgba(214, 194, 166, 0.72)',
    '--shadow-nav': 'rgba(49, 38, 24, 0.14)',
    '--button-soft-bg': '#f0e3d2',
    '--button-soft-bg-active': '#e8d7c2',
    '--button-soft-text': '#0a747e',
    '--accent-primary': '#008792',
    '--avatar-grad-start': '#fbf3e7',
    '--avatar-grad-end': '#edd3b4',
    '--avatar-border': '#e1bf96',
    '--avatar-text': '#6d5641',
    '--switch-active-border': '#35aab2',
  },
}

export const DUNHUANG_APSARAS_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'dunhuangApsaras',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#19150f',
    '--bg-surface': '#241e16',
    '--bg-surface-alt': '#2d251b',
    '--bg-surface-muted': '#342b1f',
    '--bg-soft': '#3b3123',
    '--text-primary': '#efe4d5',
    '--text-strong': '#f8ecdb',
    '--text-secondary': '#c4b49d',
    '--text-muted': '#b4a18a',
    '--text-accent': '#8fd0d5',
    '--text-on-accent': '#092126',
    '--border-soft': '#4b3d2b',
    '--border-muted': '#5c4a34',
    '--border-strong': '#6e583c',
    '--overlay-glass': 'rgba(33, 27, 20, 0.78)',
    '--overlay-panel': 'rgba(45, 37, 27, 0.8)',
    '--overlay-border-top': 'rgba(115, 92, 62, 0.74)',
    '--shadow-nav': 'rgba(10, 8, 5, 0.5)',
    '--button-soft-bg': '#4f3f2b',
    '--button-soft-bg-active': '#624f36',
    '--button-soft-text': '#d8c6ac',
    '--accent-primary': '#2ca3ac',
    '--avatar-grad-start': '#4a3a27',
    '--avatar-grad-end': '#644f35',
    '--avatar-border': '#776040',
    '--avatar-text': '#ead4b6',
    '--switch-active-border': '#73c3c8',
  },
}

export const AUTUMN_OSMANTHUS_LIGHT_THEME_PRESET: GlobalThemePreset = {
  family: 'autumnOsmanthus',
  mode: 'light',
  cssVariables: {
    '--bg-page': '#f9f3e8',
    '--bg-surface': '#fffdfa',
    '--bg-surface-alt': '#fdf7ee',
    '--bg-surface-muted': '#faefd9',
    '--bg-soft': '#f5e6c8',
    '--text-primary': '#3f2f1a',
    '--text-strong': '#31220f',
    '--text-secondary': '#7b6241',
    '--text-muted': '#8d7150',
    '--text-accent': '#d28a1d',
    '--text-on-accent': '#fff8ec',
    '--border-soft': '#eddcbf',
    '--border-muted': '#f2e5cd',
    '--border-strong': '#e2cda8',
    '--overlay-glass': 'rgba(255, 249, 239, 0.64)',
    '--overlay-panel': 'rgba(255, 252, 245, 0.78)',
    '--overlay-border-top': 'rgba(228, 200, 156, 0.72)',
    '--shadow-nav': 'rgba(58, 40, 13, 0.14)',
    '--button-soft-bg': '#f8e8ca',
    '--button-soft-bg-active': '#f3ddb4',
    '--button-soft-text': '#9f6412',
    '--accent-primary': '#d28a1d',
    '--avatar-grad-start': '#fff7e9',
    '--avatar-grad-end': '#f2d797',
    '--avatar-border': '#e9c47a',
    '--avatar-text': '#7a5a32',
    '--switch-active-border': '#e0a446',
  },
}

export const AUTUMN_OSMANTHUS_DARK_THEME_PRESET: GlobalThemePreset = {
  family: 'autumnOsmanthus',
  mode: 'dark',
  cssVariables: {
    '--bg-page': '#1d150c',
    '--bg-surface': '#2a1f12',
    '--bg-surface-alt': '#352817',
    '--bg-surface-muted': '#3f2f1b',
    '--bg-soft': '#483621',
    '--text-primary': '#f3e5cf',
    '--text-strong': '#fbeedb',
    '--text-secondary': '#ccb18a',
    '--text-muted': '#bda17c',
    '--text-accent': '#f3c67f',
    '--text-on-accent': '#2e1a08',
    '--border-soft': '#584127',
    '--border-muted': '#6a4e2f',
    '--border-strong': '#7b5c36',
    '--overlay-glass': 'rgba(39, 29, 18, 0.78)',
    '--overlay-panel': 'rgba(53, 40, 25, 0.8)',
    '--overlay-border-top': 'rgba(130, 99, 57, 0.74)',
    '--shadow-nav': 'rgba(12, 8, 3, 0.5)',
    '--button-soft-bg': '#594126',
    '--button-soft-bg-active': '#6d512f',
    '--button-soft-text': '#f2d1a0',
    '--accent-primary': '#da9a33',
    '--avatar-grad-start': '#533c22',
    '--avatar-grad-end': '#6d4f2d',
    '--avatar-border': '#846138',
    '--avatar-text': '#f1d6ae',
    '--switch-active-border': '#e1b165',
  },
}

const PRESET_MAP: Record<GlobalThemeFamily, Record<ResolvedGlobalThemeMode, GlobalThemePreset>> = {
  default: {
    light: DEFAULT_LIGHT_THEME_PRESET,
    dark: DEFAULT_DARK_THEME_PRESET,
  },
  bambooGrove: {
    light: BAMBOO_GROVE_LIGHT_THEME_PRESET,
    dark: BAMBOO_GROVE_DARK_THEME_PRESET,
  },
  palacePlum: {
    light: PALACE_PLUM_LIGHT_THEME_PRESET,
    dark: PALACE_PLUM_DARK_THEME_PRESET,
  },
  mistyJiangnan: {
    light: MISTY_JIANGNAN_LIGHT_THEME_PRESET,
    dark: MISTY_JIANGNAN_DARK_THEME_PRESET,
  },
  luoyangPeony: {
    light: LUOYANG_PEONY_LIGHT_THEME_PRESET,
    dark: LUOYANG_PEONY_DARK_THEME_PRESET,
  },
  dunhuangApsaras: {
    light: DUNHUANG_APSARAS_LIGHT_THEME_PRESET,
    dark: DUNHUANG_APSARAS_DARK_THEME_PRESET,
  },
  autumnOsmanthus: {
    light: AUTUMN_OSMANTHUS_LIGHT_THEME_PRESET,
    dark: AUTUMN_OSMANTHUS_DARK_THEME_PRESET,
  },
}

export function getGlobalThemePreset(mode: ResolvedGlobalThemeMode, family: GlobalThemeFamily = 'default') {
  return PRESET_MAP[family][mode]
}
