import { rmSync } from 'node:fs'
import { extname } from 'node:path'
import {
  releaseArtifactDir,
  rootDir,
  versionsJsonPath,
  VERSION_PATTERN,
} from './constants.mjs'
import { findLatestIpa, prepareAndroidReleaseAsset, prepareIosReleaseAsset } from './assets.mjs'
import {
  ensureCleanWorktree,
  ensureGitHubAuth,
  ensureMainBranch,
  ensureTagNotExists,
  getGitStatusSnapshot,
  stageCommitAndTag,
} from './gitFlow.mjs'
import { publishGithubRelease } from './githubRelease.mjs'
import { resolveReleaseNote, writeReleaseNoteFile } from './notes.mjs'
import { parseReleaseOptions } from './options.mjs'
import { askHidden, askText, askYesNo } from './prompt.mjs'
import { extractRepoInfo } from './repo.mjs'
import {
  buildR2LatestVersionsObjectKey,
  buildR2PublicUrl,
  buildR2ReleaseObjectKey,
  uploadAndVerifyReleaseAssetToR2,
} from './r2.mjs'
import { bootstrapR2EnvFile, loadR2Config, shouldBootstrapR2EnvFile } from './r2Config.mjs'
import { calculateFileMetadata, runFile } from './shared.mjs'
import {
  updatePackageVersionFiles,
  updateVersionsJson,
  validateTargetVersion,
} from './versioning.mjs'

function getTargetPlatforms(releaseOptions) {
  return Object.entries(releaseOptions.platforms)
    .filter(([, enabled]) => enabled)
    .map(([platform]) => platform)
}

function buildR2Plan({ releaseOptions, nextVersion, r2Config }) {
  const assetUrls = {}
  const manifestObjectKeys = []
  if (!r2Config) {
    return { assetUrls, manifestObjectKeys }
  }

  const versionedManifestObjectKey = buildR2ReleaseObjectKey({
    keyPrefix: r2Config.keyPrefix,
    version: nextVersion,
    fileName: 'versions.json',
  })
  const latestManifestObjectKey = buildR2LatestVersionsObjectKey({
    keyPrefix: r2Config.keyPrefix,
  })
  manifestObjectKeys.push(versionedManifestObjectKey, latestManifestObjectKey)
  assetUrls.versions = buildR2PublicUrl({
    publicBaseUrl: r2Config.publicBaseUrl,
    objectKey: versionedManifestObjectKey,
  })
  assetUrls.latestVersions = buildR2PublicUrl({
    publicBaseUrl: r2Config.publicBaseUrl,
    objectKey: latestManifestObjectKey,
  })

  if (releaseOptions.platforms.android) {
    const objectKey = buildR2ReleaseObjectKey({
      keyPrefix: r2Config.keyPrefix,
      version: nextVersion,
      fileName: `qmm-v${nextVersion}.apk`,
    })
    assetUrls.apk = buildR2PublicUrl({ publicBaseUrl: r2Config.publicBaseUrl, objectKey })
  }

  if (releaseOptions.platforms.ios) {
    const objectKey = buildR2ReleaseObjectKey({
      keyPrefix: r2Config.keyPrefix,
      version: nextVersion,
      fileName: `qmm-v${nextVersion}.ipa`,
    })
    assetUrls.ipa = buildR2PublicUrl({ publicBaseUrl: r2Config.publicBaseUrl, objectKey })
  }

  return { assetUrls, manifestObjectKeys }
}

function printDryRun({ nextVersion, tag, targetPlatforms, releaseOptions, owner, repo, releaseNote }) {
  console.log('Release dry run passed. No files were changed and nothing was uploaded.')
  console.log(`Version: ${nextVersion}`)
  console.log(`Tag: ${tag}`)
  console.log(`Repository: ${owner}/${repo}`)
  console.log(`Platforms: ${targetPlatforms.join(', ')}`)
  console.log(`Asset destination: GitHub Release${releaseOptions.assetSource === 'r2' ? ' + Cloudflare R2' : ''}`)
  console.log(`Release note: ${releaseNote ? 'provided' : 'generated by GitHub'}`)
  console.log('Planned tracked files:')
  console.log('- package.json')
  console.log('- package-lock.json')
  console.log('- versions.json')
  console.log('- src/generated/thirdPartyLicenses.ts')
  console.log('- android/app/build.gradle')
  console.log('- ios/App/App.xcodeproj/project.pbxproj')
  console.log('- external/survive-in-scut (gitlink, only if already changed deliberately)')
  if (releaseNote) {
    console.log(`- .release-notes/${tag}.md`)
  }
  console.log('Planned untracked release artifacts:')
  for (const platform of targetPlatforms) {
    console.log(`- artifacts/release/qmm-v${nextVersion}.${platform === 'android' ? 'apk' : 'ipa'}`)
  }
}

function collectAssetMetadata(preparedAssets) {
  const metadata = {}
  for (const assetPath of preparedAssets) {
    const extension = extname(assetPath).toLowerCase()
    if (extension === '.apk') {
      metadata.apk = calculateFileMetadata(assetPath)
    }
    if (extension === '.ipa') {
      metadata.ipa = calculateFileMetadata(assetPath)
    }
  }
  return metadata
}

async function uploadR2Assets({ preparedAssets, manifestObjectKeys, nextVersion, r2Config }) {
  for (const assetPath of preparedAssets) {
    const fileName = assetPath.split(/[/\\]/).pop()
    if (!fileName) {
      throw new Error(`Unable to resolve asset file name from path: ${assetPath}`)
    }

    const objectKey = buildR2ReleaseObjectKey({
      keyPrefix: r2Config.keyPrefix,
      version: nextVersion,
      fileName,
    })
    const uploaded = await uploadAndVerifyReleaseAssetToR2({
      localFilePath: assetPath,
      objectKey,
      r2Config,
    })
    console.log(`Uploaded and verified ${fileName}: ${uploaded.url}`)
  }

  for (const objectKey of manifestObjectKeys) {
    const uploaded = await uploadAndVerifyReleaseAssetToR2({
      localFilePath: versionsJsonPath,
      objectKey,
      r2Config,
    })
    console.log(`Uploaded and verified versions.json: ${uploaded.url}`)
  }
}

async function main() {
  const releaseOptions = parseReleaseOptions()
  const nextVersion = releaseOptions.version
  const { packageJson } = validateTargetVersion(nextVersion)
  const tag = `v${nextVersion}`
  if (!VERSION_PATTERN.test(nextVersion)) {
    throw new Error(`Invalid version code: ${nextVersion}. Expected format: x.y.z`)
  }

  ensureMainBranch()
  ensureTagNotExists(tag)
  ensureCleanWorktree()
  ensureGitHubAuth()

  const targetPlatforms = getTargetPlatforms(releaseOptions)
  const { owner, repo } = extractRepoInfo()
  const repoSlug = `${owner}/${repo}`
  const releaseNote = resolveReleaseNote({
    note: releaseOptions.note,
    noteFile: releaseOptions.noteFile,
  })

  let r2Config = null
  if (releaseOptions.assetSource === 'r2') {
    if (releaseOptions.dryRun && shouldBootstrapR2EnvFile()) {
      throw new Error('R2 dry run requires existing R2_ENV or R2 environment variables; no config file was created.')
    }

    if (!releaseOptions.dryRun && shouldBootstrapR2EnvFile()) {
      await bootstrapR2EnvFile({ askText, askHidden })
    }
    r2Config = loadR2Config()
  }

  const initialStatus = getGitStatusSnapshot()
  if (releaseOptions.dryRun) {
    printDryRun({ nextVersion, tag, targetPlatforms, releaseOptions, owner, repo, releaseNote })
    const finalStatus = getGitStatusSnapshot()
    if (finalStatus !== initialStatus) {
      throw new Error('Dry run changed the Git worktree unexpectedly.')
    }
    return
  }

  const publishedAt = new Date().toISOString()
  const r2Plan = buildR2Plan({ releaseOptions, nextVersion, r2Config })

  runFile('git', ['submodule', 'update', '--init', '--recursive'], rootDir)
  updatePackageVersionFiles(packageJson, nextVersion)
  updateVersionsJson({
    version: nextVersion,
    tag,
    owner,
    repo,
    hasAndroidAsset: releaseOptions.platforms.android,
    hasIosAsset: releaseOptions.platforms.ios,
    r2AssetUrls: r2Plan.assetUrls,
    publishedAt,
  })
  runFile('node', ['scripts/syncNativeVersion.mjs'], rootDir)
  runFile('npm', ['run', 'check'], rootDir)

  const preparedAssets = []
  if (releaseOptions.platforms.android) {
    runFile('npm', ['run', 'build:android'], rootDir)
    runFile('npx', ['cap', 'open', 'android'], rootDir)
    if (!await askYesNo('Have you finished building the APK in Android Studio? [y/N]: ')) {
      throw new Error('APK build was not confirmed. Release process stopped.')
    }
    preparedAssets.push(prepareAndroidReleaseAsset(nextVersion))
  }

  if (releaseOptions.platforms.ios) {
    runFile('npm', ['run', 'build:ios'], rootDir)
    runFile('npx', ['cap', 'open', 'ios'], rootDir)
    if (!await askYesNo('Have you finished exporting the IPA in Xcode? [y/N]: ')) {
      throw new Error('IPA export was not confirmed. Release process stopped.')
    }
    const manualIpaPath = await askText('Optional: enter IPA absolute path (press Enter to auto-detect): ')
    preparedAssets.push(prepareIosReleaseAsset(nextVersion, manualIpaPath || findLatestIpa()))
  }

  if (preparedAssets.length === 0) {
    throw new Error('No release assets were prepared.')
  }

  const assetMetadata = collectAssetMetadata(preparedAssets)
  updateVersionsJson({
    version: nextVersion,
    tag,
    owner,
    repo,
    hasAndroidAsset: releaseOptions.platforms.android,
    hasIosAsset: releaseOptions.platforms.ios,
    r2AssetUrls: r2Plan.assetUrls,
    assetMetadata,
    publishedAt,
  })

  const noteFilePath = writeReleaseNoteFile({ tag, content: releaseNote })
  if (r2Config) {
    await uploadR2Assets({
      preparedAssets,
      manifestObjectKeys: r2Plan.manifestObjectKeys,
      nextVersion,
      r2Config,
    })
  }

  stageCommitAndTag({ version: nextVersion, tag, noteFilePath })
  publishGithubRelease({
    tag,
    repoSlug,
    assetPaths: [...preparedAssets, versionsJsonPath],
    noteFilePath,
  })

  rmSync(releaseArtifactDir, { recursive: true, force: true })
  console.log(`Release published and verified: https://github.com/${repoSlug}/releases/tag/${tag}`)
}

await main()
