import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, extname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const currentDir = dirname(fileURLToPath(import.meta.url))
const rootDir = resolve(currentDir, '..')
const appSourceDir = resolve(rootDir, 'src')
const manualTodoFile = resolve(rootDir, 'external/survive-in-scut/docs/others/todo.md')
const outputFile = resolve(rootDir, 'src/generated/todoSnapshot.ts')

function walkFiles(dirPath) {
  const entries = readdirSync(dirPath, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    if (entry.name === 'generated') {
      continue
    }

    const fullPath = resolve(dirPath, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkFiles(fullPath))
      continue
    }

    const extension = extname(entry.name)
    if (extension === '.ts' || extension === '.tsx') {
      files.push(fullPath)
    }
  }

  return files
}

function extractTodoMessage(rawLine) {
  const todoMatch = rawLine.match(/TODO([:：])/)
  if (!todoMatch) {
    return null
  }

  const todoIndex = todoMatch.index ?? -1
  if (todoIndex < 0) {
    return null
  }

  const prefix = rawLine.slice(0, todoIndex)
  const hasCommentPrefix =
    prefix.includes('//') ||
    prefix.includes('/*') ||
    rawLine.trimStart().startsWith('*')

  if (!hasCommentPrefix) {
    return null
  }

  const message = rawLine.slice(todoIndex + 5).trimStart()
  return message.length > 0 ? message : null
}

function collectAppTodos() {
  const sourceFiles = walkFiles(appSourceDir).sort((a, b) => a.localeCompare(b))
  const todos = []

  for (const filePath of sourceFiles) {
    const content = readFileSync(filePath, 'utf8')
    const lines = content.split(/\r?\n/)

    for (const line of lines) {
      const message = extractTodoMessage(line)
      if (!message) {
        continue
      }

      todos.push(message)
    }
  }

  return todos
}

function collectManualTodos() {
  try {
    const content = readFileSync(manualTodoFile, 'utf8')
    const lines = content.split(/\r?\n/)
    const todos = []

    for (const line of lines) {
      const match = line.match(/TODO[:：]\s*(.+)$/)
      if (!match) {
        continue
      }

      const message = match[1].trim()
      if (message.length > 0) {
        todos.push(message)
      }
    }

    return todos
  } catch {
    return []
  }
}

function toTsArray(name, items) {
  const body = items.map((item) => `  ${JSON.stringify(item)},`).join('\n')
  return `export const ${name}: string[] = [\n${body}\n]\n`
}

function generateSnapshot() {
  const appTodos = collectAppTodos()
  const manualTodos = collectManualTodos()

  const output = [
    '// This file is generated by scripts/generateTodoSnapshot.mjs',
    toTsArray('APP_TODO_ITEMS', appTodos),
    toTsArray('MANUAL_TODO_ITEMS', manualTodos),
  ].join('\n')

  mkdirSync(dirname(outputFile), { recursive: true })
  writeFileSync(outputFile, output)
}

generateSnapshot()
